name: Checking
on:
  push:
    branches:
      - master
      - siberblog-patch-1
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud2:
    name: SonarCloudResults 
    runs-on: this_label
    steps:
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS 
